baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: brianhanson.net
primary: true
siteGroup: ab6cfcb5-1496-4859-90dd-f4ee7522a2b0 # brianhanson.net
sortOrder: 1
