fieldLayouts:
  5e6921f1-868c-48f0-8c11-35dfc39362ef:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 218e8fcf-3aa3-4476-aaef-0656be085d34
            warning: null
            width: 100
          -
            fieldUid: d443d31b-4223-4133-ad4a-2925a6dc9aeb # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86206298-042b-483f-9424-2f6c3c951cb1
            warning: null
            width: 100
          -
            fieldUid: 855d752d-967a-4e1b-b388-3720f3eb4156 # Blog Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42875ea0-463c-4d4c-a412-ab8592ab8853
            warning: null
            width: 100
          -
            fieldUid: 69e37b26-a017-43d3-950b-4537e1e35394 # Markdown
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57e7174c-818a-4f93-b236-d42a0b9b3dde
            warning: null
            width: 100
        name: Content
        uid: 8d16a8d1-abbc-49cc-810a-8aaeeb7835bc
handle: default
hasTitleField: true
name: Default
section: ff5a1924-3412-4202-a2ed-204f8b93f9b0 # Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
