fieldLayouts:
  ef0f61c8-a33e-463c-8f7b-df63cf256398:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5f9c723a-f16b-4881-8cb0-9c6fce4ea848
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 855d752d-967a-4e1b-b388-3720f3eb4156 # Blog Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eb7ef3c-e18a-4a28-9a28-b8da9ea026af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 465d699c-2d42-443d-8217-abd0c88a4f99 # Lede
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ddb61bf-db28-42bf-ac52-0bbde8bbbc2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69e37b26-a017-43d3-950b-4537e1e35394 # Markdown
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21e3d6f0-d9d7-4c80-8dc0-15b5adeac9ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47984462-aeed-4040-af98-6d6ceb70701b # External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7c7c1f3-3dc0-420f-ae6b-c02f790a4f16
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b068d7d-0edf-4e3e-8320-be9cf6d7fee8
        userCondition: null
handle: link
hasTitleField: true
name: Link
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
