columnSuffix: ejcgrkvy
contentColumnType: datetime
fieldGroup: 5fc3e5f8-434c-47be-8a3c-ae0dae33cdb7 # Common
handle: finishDate
instructions: null
name: 'Finish Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
