columnSuffix: fmmoajdk
contentColumnType: string(255)
handle: imageLink
instructions: null
name: 'Image Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
