columnSuffix: fmmoajdk
contentColumnType: string(255)
fieldGroup: 5fc3e5f8-434c-47be-8a3c-ae0dae33cdb7 # Common
handle: imageLink
instructions: null
name: 'Image Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
