columnSuffix: nashpiyt
contentColumnType: smallint(1)
handle: rating
instructions: null
name: Rating
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 5
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
