columnSuffix: nashpiyt
contentColumnType: smallint(1)
fieldGroup: 5fc3e5f8-434c-47be-8a3c-ae0dae33cdb7 # Common
handle: rating
instructions: null
name: Rating
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 5
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
