defaultPlacement: end
fieldLayouts:
  c51a3a5e-22e4-478c-84ec-1dfc679f58d9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 75455905-5cbe-46d2-a458-c25eb57ab24f
            warning: null
            width: 100
        name: Content
        uid: 587dac37-9010-46a8-baa7-97fc2e582476
handle: categories
name: Categories
siteSettings:
  91c831e2-b264-4a09-a1c9-25faa8ef71c1: # Brian Hanson
    hasUrls: true
    template: null
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: d09d5fa2-a030-4ac2-b9bb-ae4af74ae965
