defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  91c831e2-b264-4a09-a1c9-25faa8ef71c1: # Brian Hanson
    enabledByDefault: false
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
